[tox]
requires =
    tox-uv
envlist =
    pre-commit
    mypy
    twinecheck
    py310
    py311
    py312
    py313
    py314
    pypy3

[testenv]
deps =
    coverage >= 7.10.6
    pytest
    pytest-cov >= 7.0.0
commands =
    pytest {posargs:--cov-config=pyproject.toml --cov=formerly --cov-report=term-missing --cov-report=xml --junitxml=testenv.junit.xml -o junit_family=legacy formerly tests}

[testenv:mypy]
basepython = python3.10
deps =
    {[testenv]deps}
    mypy==2.4.0
commands =
    mypy {posargs:formerly tests}

[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run {posargs:--all-files --show-diff-on-failure}
skip_install = true

[testenv:twinecheck]
deps =
    build==1.6.1
    twine==7.0.0
commands =
    python -m build --sdist
    twine check dist/*
